name: 'Create Loft Space'
description: 'GitHub Action to create a Loft Space'
author: loft.sh
inputs:
  name:
    required: true
    description: 'The name of the Space to create'
  account:
    required: false
    description: 'The cluster account to use'
  cluster:
    required: false
    description: 'The cluster to use'
  delete-after:
    required: false
    description: 'If set to non zero, will tell loft to delete the space after specified seconds of inactivity'
  sleep-after:
    required: false
    description: 'If set to non zero, will tell the space to sleep after specified seconds of inactivity'
  disable-direct-cluster-endpoint:
    required: false
    description: 'When enabled does not use an available direct cluster endpoint to connect to the space'
  auto-cleanup:
    required: false
    description: 'Delete the Space after the job run. Defaults to true'
    default: false
runs:
  using: 'node12'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
