name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  # test-error-without-loft:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: ./
  #       continue-on-error: true
  #       with:
  #         name: create-myspace-${{ matrix.os }}
  #     - run: loft list spaces
  test-automatic-delete:
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: loft-sh/setup-loft@main
        with:
          url: ${{ secrets.LOFT_URL }}
          access-key: ${{ secrets.LOFT_ACCESS_KEY }}
      - uses: ./
        with:
          name: create-myspace-${{ matrix.os }}
      - run: loft list spaces
  test-manual-delete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: loft-sh/setup-loft@main
        with:
          url: ${{ secrets.LOFT_URL }}
          access-key: ${{ secrets.LOFT_ACCESS_KEY }}
      - uses: ./
        with:
          name: create-myspace-manual-delete
          auto-cleanup: false
      - run: loft list spaces
      - run: loft delete space create-myspace-manual-delete
  test-delete-after:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: loft-sh/setup-loft@main
        with:
          url: ${{ secrets.LOFT_URL }}
          access-key: ${{ secrets.LOFT_ACCESS_KEY }}
      - uses: ./
        with:
          name: create-myspace-delete-after
          delete-after: 60
      - run: loft list spaces
  test-sleep-after:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: loft-sh/setup-loft@main
        with:
          url: ${{ secrets.LOFT_URL }}
          access-key: ${{ secrets.LOFT_ACCESS_KEY }}
      - uses: ./
        with:
          name: create-myspace-sleep-after
          sleep-after: 60
      - run: loft list spaces
  test-disable-direct-cluster-endpoint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: loft-sh/setup-loft@main
        with:
          url: ${{ secrets.LOFT_URL }}
          access-key: ${{ secrets.LOFT_ACCESS_KEY }}
      - uses: ./
        with:
          name: create-myspace-disable-direct-cluster-endpoint
          disable-direct-cluster-endpoint: true
      - run: loft list spaces